export interface IeltsEssay {
  id: string;
  topic: string;
  question: string;
  essay: string;
}

// 四篇雅思 Task 2 8 分参考范文，长度均控制在 ~1700–1900 字符
export const IELTS_ESSAYS: readonly IeltsEssay[] = [
  {
    id: "education",
    topic: "Education",
    question:
      "Some people believe that online learning will eventually replace traditional classroom education. To what extent do you agree or disagree?",
    essay:
      "The proposition that online learning will entirely supplant traditional classroom education is, in my view, an overstatement. While digital platforms have transformed how knowledge is delivered, the physical classroom retains pedagogical and social functions that screens cannot fully replicate. It is undeniable that online learning offers substantial advantages. Recorded lectures can be paused, replayed, and accessed from anywhere, allowing learners to study at their own pace. For working adults and students in remote regions, this flexibility removes geographical and temporal barriers that traditional institutions impose. Furthermore, well-designed online courses can reach thousands of students simultaneously, making expert instruction more affordable than ever before. However, several aspects of education remain stubbornly resistant to digitization. Laboratory experiments, clinical training, and performance-based disciplines such as music and surgery require hands-on supervision that video calls cannot provide. Equally important is the social dimension of schooling: spontaneous discussions in corridors, peer collaboration on group projects, and the mentoring relationships that form between teachers and students. These intangible elements often shape character and motivation more profoundly than the curriculum itself. A more plausible future is a hybrid model in which online and in-person methods complement each other. Theoretical content can be delivered digitally, freeing classroom time for practical work, debate, and individualized feedback. Many universities have already adopted this approach with measurable success. In conclusion, although online learning will continue to expand and improve, it is unlikely to render traditional classrooms obsolete. The most effective educational systems of the coming decades will likely blend the convenience of digital tools with the irreplaceable human contact of physical schools.",
  },
  {
    id: "environment",
    topic: "Environment",
    question:
      "Some argue that protecting the environment is the responsibility of governments, while others believe individuals should take action. Discuss both views and give your own opinion.",
    essay:
      "Environmental protection has emerged as one of the defining challenges of our era, and a vigorous debate continues over whether the burden of action should fall primarily on governments or on individual citizens. In my opinion, both bear genuine responsibility, but the scale of the crisis demands that government leadership take precedence. Those who argue that governments must lead emphasize that only state authorities possess the legal, financial, and coordinating power required for systemic change. Regulations on industrial emissions, investment in renewable energy infrastructure, and international treaties on biodiversity are simply beyond the reach of private citizens. Without enforceable policy, even the most conscientious consumers cannot offset the impact of polluting industries. Proponents of personal responsibility, however, raise an equally important point. Daily decisions about transportation, diet, and consumption aggregate into enormous ecological footprints. Recycling household waste, reducing meat intake, and choosing energy-efficient appliances are concrete steps that collectively make a measurable difference. Moreover, citizens who adopt sustainable habits create political pressure for stronger environmental legislation by demonstrating that green alternatives are viable and popular. In reality, these two positions are complementary rather than opposed. Governments set the framework, while individuals operate within it. A carbon tax becomes effective only when households respond by switching to cleaner alternatives; conversely, individual efforts achieve their full potential only when supported by accessible public transport, recycling infrastructure, and clear product labeling. In conclusion, the environmental crisis is too vast to be solved by either party alone. Governments must legislate boldly and invest in long-term solutions, but individuals must also embrace lifestyle changes. The most effective progress will come from a partnership in which policy and personal behavior reinforce each other.",
  },
  {
    id: "social-media",
    topic: "Social Media",
    question:
      "Many people now use social media to communicate. Do the advantages of this trend outweigh the disadvantages?",
    essay:
      "Social media has reshaped human communication so profoundly that some commentators describe it as the most consequential technological shift since the printing press. Despite genuine drawbacks, I believe its overall benefits outweigh its costs, provided that users approach these platforms with awareness. The advantages of social media communication are substantial. Geographic distance, once a serious obstacle to maintaining relationships, has been effectively dissolved. Families separated by migration can share daily moments through messaging apps, while professional networks span continents at negligible cost. In emergencies such as natural disasters, platforms have repeatedly proven their value as channels for warnings, coordination, and mutual aid. Moreover, marginalized voices that traditional media historically excluded now find audiences directly, accelerating social progress on issues from civil rights to mental health. Nevertheless, the disadvantages cannot be dismissed. Algorithm-driven feeds promote outrage and misinformation because such content maximizes engagement, contributing to political polarization and the erosion of shared facts. Excessive use is associated with anxiety and reduced attention spans, particularly among adolescents. Privacy concerns also persist, as personal data is routinely harvested and monetized in ways most users barely understand. These problems, however, are not inherent to social media itself but rather to its current business models and our collective inexperience with the medium. Education in digital literacy, regulatory action against deceptive design patterns, and conscious habits such as scheduled offline time can mitigate the harms while preserving the benefits. In conclusion, social media has expanded human connection and democratized expression on an unprecedented scale. The risks are real and warrant serious attention, but with thoughtful regulation and personal discipline, the advantages clearly outweigh the disadvantages for most users.",
  },
  {
    id: "remote-work",
    topic: "Remote Work",
    question:
      "Working from home has become more common in recent years. Do you think this development has more positive or negative effects on employees and companies?",
    essay:
      "The proportion of employees working remotely has risen dramatically over the past few years, accelerated by the global pandemic and enabled by mature collaboration technologies. While the shift brings genuine challenges for both workers and employers, I believe its positive effects outweigh the negative ones when implemented thoughtfully. For employees, the most obvious benefit is the elimination of the daily commute. Hours previously lost on crowded trains or congested roads can be redirected toward family, exercise, or rest, leading to measurable improvements in well-being. Geographical flexibility also widens career options: a software engineer in a small town can work for a company headquartered in another country without uprooting their life. Many parents, in particular, report that home working has made it possible to balance professional ambition with caregiving responsibilities that were previously incompatible with office hours. Companies derive comparable advantages. Office space is expensive, and reducing real estate costs frees capital for investment in products and people. Talent pools expand beyond local markets, allowing employers to recruit the best candidates regardless of location. Studies of remote-friendly firms have consistently found that productivity is at least equal to traditional offices, and employee retention is often higher because workers value the flexibility. The disadvantages, however, deserve acknowledgment. Junior staff lose the informal mentoring that happens organically in shared workspaces, and team cohesion can erode without face-to-face contact. The boundary between work and personal life often blurs, leading some employees to work longer hours than before. Companies must therefore invest in structured onboarding, periodic in-person gatherings, and clear policies on availability to prevent burnout. In conclusion, remote work brings substantial benefits in flexibility, cost, and access to talent. The risks are real but manageable, and a well-designed hybrid model can capture most of the advantages while addressing the drawbacks.",
  },
] as const;
